package edu.connexion3a8.services.collaboration;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import edu.connexion3a8.entities.collaboration.Project;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class PdfExportService {

    /**
     * Generates a beautiful PDF containing the AI Explanation of the project.
     * 
     * @param project       The project being analyzed.
     * @param aiExplanation The text generated by the AI
     * @return the absolute path of the generated PDF file, or null if it failed.
     */
    public static String generateProjectAiReport(Project project, String aiExplanation) {
        String userHome = System.getProperty("user.home");
        File dir = new File(userHome, "Downloads/InvestiReports");
        if (!dir.exists()) {
            dir.mkdirs();
        }

        String fileName = "ProjectReport_" + project.getProjectId() + "_" + System.currentTimeMillis() + ".pdf";
        File pdfFile = new File(dir, fileName);

        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(pdfFile));
            document.open();

            // Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, Color.decode("#456990"));
            Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Color.decode("#9B7E46"));
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.DARK_GRAY);
            Font highlightFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.decode("#A62639"));

            // Title
            Paragraph title = new Paragraph("AI Investment Analysis", titleFont);
            title.setAlignment(Paragraph.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Project Details
            document.add(new Paragraph("Project Title: " + project.getTitle(), subtitleFont));
            document.add(new Paragraph("Category: " + project.getCategory(), highlightFont));
            document.add(new Paragraph("Requested Amount: $" + String.format("%.2f", project.getAmountRequested()),
                    bodyFont));
            document.add(new Paragraph("Equity Offered: " + project.getEquityOffered() + "%", bodyFont));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Original Description:", subtitleFont));
            document.add(new Paragraph(project.getDescription(), bodyFont));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("-------------------------------------------------------------------"));
            document.add(new Paragraph(" "));

            // AI Explanation
            Paragraph aiTitle = new Paragraph("Detailed AI Breakdown", subtitleFont);
            aiTitle.setSpacingAfter(10);
            document.add(aiTitle);

            Paragraph aiBody = new Paragraph(aiExplanation, bodyFont);
            document.add(aiBody);

            document.close();
            return pdfFile.getAbsolutePath();
        } catch (DocumentException | IOException e) {
            e.printStackTrace();
            return null;
        }
    }
}
