# SMTP Configuration
smtp.host=smtp.gmail.com
smtp.port=587
smtp.email=investi.platform2000@gmail.com
smtp.password=sach nzim glfo oaui

# Database Configuration (VPS Remote Connection)
db.url=jdbc:mysql://54.90.222.165:3306/3a8?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=investi
db.password=investi123
