# SMTP Configuration
smtp.host=smtp.gmail.com
smtp.port=587
smtp.email=investi.platform2000@gmail.com
smtp.password=sach nzim glfo oaui

# Database Configuration
db.url=jdbc:mysql://localhost:3306/3a8
db.user=root
db.password=
